#ifndef COM_ONEISH_STRANGE_REFLECTIONS_H
#define COM_ONEISH_STRANGE_REFLECTIONS_H

// reflections

#include "strange_any_r.h"
#include "strange_symbol_r.h"
#include "strange_cat_r.h"
#include "strange_kind_r.h"
#include "strange_forward_const_iterator_r.h"
#include "strange_forward_const_iterator_data_r.h"
#include "strange_forward_iterator_r.h"
#include "strange_forward_iterator_data_r.h"
#include "strange_misunderstanding_r.h"
#include "strange_range_r.h"
#include "strange_range_of_r.h"
#include "strange_collection_r.h"
#include "strange_inventory_r.h"
#include "strange_herd_r.h"
#include "strange_ordered_herd_r.h"
#include "strange_unordered_herd_r.h"
#include "strange_shoal_r.h"
#include "strange_ordered_shoal_r.h"
#include "strange_unordered_shoal_r.h"
#include "strange_number_r.h"
#include "strange_number_data_r.h"
#include "strange_lake_r.h"
#include "strange_brook_r.h"
#include "strange_flock_r.h"
#include "strange_squad_r.h"
#include "strange_river_r.h"
#include "strange_bidirectional_const_iterator_r.h"
#include "strange_bidirectional_const_iterator_data_r.h"
#include "strange_bidirectional_iterator_r.h"
#include "strange_bidirectional_iterator_data_r.h"
#include "strange_random_access_const_iterator_r.h"
#include "strange_random_access_const_iterator_data_r.h"
#include "strange_random_access_iterator_r.h"
#include "strange_random_access_iterator_data_r.h"
#include "strange_data_r.h"
#include "strange_token_r.h"
#include "strange_parser_r.h"
#include "strange_operation_r.h"
#include "strange_expression_r.h"

#endif
