#ifndef COM_ONEISH_STRANGE_REFLECTIONS_H
#define COM_ONEISH_STRANGE_REFLECTIONS_H

// reflections

namespace strange
{

template<typename _ABSTRACTION_OR_THING_>
class reflection;

}

#include "strange_any_r.h"
#include "strange_thing_r.h"
#include "strange_symbol_r.h"
#include "strange_cat_r.h"
#include "strange_kind_r.h"
#include "strange_forward_const_iterator_r.h"
#include "strange_forward_const_iterator_data_r.h"
#include "strange_forward_iterator_r.h"
#include "strange_forward_iterator_data_r.h"
#include "strange_misunderstanding_r.h"
#include "strange_range_r.h"
#include "strange_collection_r.h"
#include "strange_inventory_r.h"
#include "strange_herd_r.h"
#include "strange_ordered_herd_r.h"
#include "strange_unordered_herd_r.h"
#include "strange_shoal_r.h"
#include "strange_ordered_shoal_r.h"
#include "strange_unordered_shoal_r.h"
#include "strange_number_r.h"
#include "strange_number_data_r.h"
#include "strange_lake_r.h"
#include "strange_brook_r.h"
#include "strange_flock_r.h"
#include "strange_squad_r.h"
#include "strange_river_r.h"
#include "strange_bidirectional_const_iterator_r.h"
#include "strange_bidirectional_const_iterator_data_r.h"
#include "strange_bidirectional_iterator_r.h"
#include "strange_bidirectional_iterator_data_r.h"
#include "strange_random_access_const_iterator_r.h"
#include "strange_random_access_const_iterator_data_r.h"
#include "strange_random_access_iterator_r.h"
#include "strange_random_access_iterator_data_r.h"
#include "strange_disagreement_r.h"
#include "strange_it_r.h"
#include "strange_nothing_r.h"
#include "strange_number_reference_r.h"
#include "strange_something_r.h"
#include "strange_data_r.h"
#include "strange_range_operator_r.h"
#include "strange_token_r.h"
#include "strange_tokenizer_r.h"
#include "strange_operation_r.h"
#include "strange_expression_r.h"
#include "strange_expression_local_at_r.h"
#include "strange_expression_local_insert_r.h"
#include "strange_expression_local_update_r.h"
#include "strange_expression_shared_at_r.h"
#include "strange_expression_shared_insert_r.h"
#include "strange_expression_shared_update_r.h"
#include "strange_expression_me_r.h"
#include "strange_expression_literal_r.h"
#include "strange_expression_cat_r.h"
#include "strange_expression_kind_r.h"
#include "strange_expression_invoke_r.h"
#include "strange_expression_invoke_range_r.h"
#include "strange_expression_operate_r.h"
#include "strange_expression_operate_range_r.h"
#include "strange_expression_break_r.h"
#include "strange_expression_continue_r.h"
#include "strange_expression_return_r.h"
#include "strange_expression_function_r.h"
#include "strange_expression_extraction_r.h"
#include "strange_expression_mutation_r.h"
#include "strange_expression_shared_scope_r.h"
#include "strange_expression_flock_r.h"
#include "strange_expression_shoal_r.h"
#include "strange_expression_herd_r.h"
#include "strange_expression_throw_r.h"
#include "strange_expression_catch_r.h"
#include "strange_expression_intimate_r.h"
#include "strange_expression_intimate_range_r.h"
#include "strange_expression_block_r.h"
#include "strange_expression_if_r.h"
#include "strange_expression_while_r.h"
#include "strange_expression_do_r.h"
#include "strange_expression_for_r.h"
#include "strange_expression_for_range_r.h"
#include "strange_any_creature_r.h"
#include "strange_operation_creature_r.h"
#include "strange_expression_creature_r.h"

#endif
